import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../shared/config/globals.css";
import { AppProviders } from "@/shared/providers/app-providers";

/*
src/
├── app/                    # Initialization and routing
│   ├── layout.tsx        
│   └── page.tsx         
└── shared/              
    └── providers/         # Application providers and contexts
        └── app-providers.tsx    # Main providers wrapper
*/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
